name: CI/CD Pipeline for NLP Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t my-nlp-project .

      - name: Run Container
        run: docker run --name my-nlp-container -d my-nlp-project

      - name: Print Docker Logs (Before Tests)
        run: docker logs my-nlp-container

      - name: List Files Inside Container
        run: docker exec my-nlp-container ls -R /app

      - name: Wait for Application to Start
        run: sleep 5

      - name: Run Tests
        run: docker exec my-nlp-container pytest /app/tests/

      - name: Stop and Remove Container
        run: docker stop my-nlp-container && docker rm my-nlp-container
